Checking For Updates...
Traceback (most recent call last):
  File "/home/power/HBomb/hbomb.py", line 116, in <module>
    ver = urllib.request.urlopen(                                            
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen         
    return opener.open(url, data, timeout)                                   
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open            
    response = meth(req, response)                                           
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response   
    response = self.parent.error(                                            
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error           
    return self._call_chain(*args)                                           
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain     
    result = func(*args)                                                     
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default                                                                           
    raise HTTPError(req.full_url, code, msg, hdrs, fp)                       
urllib.error.HTTPError: HTTP Error 404: Not Found          
